-- V2__catalog_schema.sql
-- Reference / catalog data: stations, trains, and the ordered stops on each train's route.

CREATE TABLE station (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10)  NOT NULL,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    CONSTRAINT uq_station_code UNIQUE (code)
);

CREATE TABLE train (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(10)  NOT NULL,
    name   VARCHAR(100) NOT NULL,
    type   VARCHAR(20)  NOT NULL,
    CONSTRAINT uq_train_number UNIQUE (number),
    CONSTRAINT ck_train_type CHECK (type IN ('SUPERFAST', 'EXPRESS', 'PASSENGER', 'RAJDHANI', 'SHATABDI', 'DURONTO'))
);

CREATE TABLE route_stop (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_id       BIGINT NOT NULL,
    station_id     BIGINT NOT NULL,
    stop_order     INT    NOT NULL,
    arrival_time   TIME,           -- NULL at the originating station
    departure_time TIME,           -- NULL at the terminating station
    distance_km    INT    NOT NULL,
    CONSTRAINT fk_route_stop_train   FOREIGN KEY (train_id)   REFERENCES train(id)   ON DELETE CASCADE,
    CONSTRAINT fk_route_stop_station FOREIGN KEY (station_id) REFERENCES station(id),
    CONSTRAINT uq_route_stop_train_order   UNIQUE (train_id, stop_order),
    CONSTRAINT uq_route_stop_train_station UNIQUE (train_id, station_id),
    CONSTRAINT ck_route_stop_order    CHECK (stop_order >= 1),
    CONSTRAINT ck_route_stop_distance CHECK (distance_km >= 0)
);

CREATE INDEX idx_route_stop_station ON route_stop(station_id);
