-- V3__scheduling_schema.sql
-- A schedule is one running of a train on a journey date. Each schedule owns its own
-- coaches and seats, plus a per-coach inventory counter used for fast availability checks.

CREATE TABLE schedule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_id     BIGINT      NOT NULL,
    journey_date DATE        NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    CONSTRAINT fk_schedule_train FOREIGN KEY (train_id) REFERENCES train(id),
    CONSTRAINT uq_schedule_train_date UNIQUE (train_id, journey_date),
    CONSTRAINT ck_schedule_status CHECK (status IN ('SCHEDULED', 'DEPARTED', 'CANCELLED', 'COMPLETED'))
);

CREATE INDEX idx_schedule_journey_date ON schedule(journey_date);

CREATE TABLE coach (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id  BIGINT      NOT NULL,
    coach_code   VARCHAR(10) NOT NULL,
    travel_class VARCHAR(10) NOT NULL,
    total_seats  INT         NOT NULL,
    CONSTRAINT fk_coach_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(id) ON DELETE CASCADE,
    CONSTRAINT uq_coach_schedule_code UNIQUE (schedule_id, coach_code),
    CONSTRAINT ck_coach_class CHECK (travel_class IN ('SL', '3A', '2A', '1A', 'CC', '2S', 'EC')),
    CONSTRAINT ck_coach_total_seats CHECK (total_seats > 0)
);

CREATE INDEX idx_coach_schedule ON coach(schedule_id);

CREATE TABLE seat (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id    BIGINT      NOT NULL,
    seat_number VARCHAR(10) NOT NULL,
    berth_type  VARCHAR(20) NOT NULL,
    CONSTRAINT fk_seat_coach FOREIGN KEY (coach_id) REFERENCES coach(id) ON DELETE CASCADE,
    CONSTRAINT uq_seat_coach_number UNIQUE (coach_id, seat_number),
    CONSTRAINT ck_seat_berth CHECK (berth_type IN ('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', 'SIDE_UPPER', 'WINDOW', 'AISLE', 'NONE'))
);

CREATE INDEX idx_seat_coach ON seat(coach_id);

-- Aggregate availability counter, one row per (schedule, coach).
-- `version` supports optimistic locking (Phase 4).
CREATE TABLE seat_inventory (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id     BIGINT NOT NULL,
    coach_id        BIGINT NOT NULL,
    available_count INT    NOT NULL,
    booked_count    INT    NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_inv_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_coach     FOREIGN KEY (coach_id)   REFERENCES coach(id)     ON DELETE CASCADE,
    CONSTRAINT uq_inv_schedule_coach UNIQUE (schedule_id, coach_id),
    -- STRUCTURAL OVERBOOKING GUARD #1 (aggregate): the available counter can never go
    -- negative. If application code ever tries to sell more than exists, the DB rejects it.
    CONSTRAINT ck_inv_available_nonneg CHECK (available_count >= 0),
    CONSTRAINT ck_inv_booked_nonneg    CHECK (booked_count >= 0)
);

CREATE INDEX idx_inv_schedule ON seat_inventory(schedule_id);
