-- V4__booking_schema.sql
-- Users, the two-phase seat-claim tables (seat_hold, booking, booking_passenger),
-- and payments. This migration also installs the per-seat structural overbooking guard.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(120) NOT NULL,
    phone         VARCHAR(20),
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT ck_user_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE booking (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnr             VARCHAR(15)   NOT NULL,
    user_id         BIGINT        NOT NULL,
    schedule_id     BIGINT        NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    total_fare      NUMERIC(10, 2) NOT NULL,
    idempotency_key VARCHAR(80),
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version         BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_booking_user     FOREIGN KEY (user_id)     REFERENCES app_user(id),
    CONSTRAINT fk_booking_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(id),
    CONSTRAINT uq_booking_pnr UNIQUE (pnr),
    -- Idempotency guard at the DB layer: a retried request carrying the same key can
    -- never create a second booking (multiple NULLs are allowed by Postgres).
    CONSTRAINT uq_booking_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_booking_status CHECK (status IN ('PENDING', 'HELD', 'CONFIRMED', 'WAITLISTED', 'RAC', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT ck_booking_fare CHECK (total_fare >= 0)
);

CREATE INDEX idx_booking_user     ON booking(user_id);
CREATE INDEX idx_booking_schedule ON booking(schedule_id);

-- A temporary claim on a seat with a TTL. Confirmed bookings keep their hold rows
-- (status CONFIRMED) so the seat stays locked for the whole life of the booking.
CREATE TABLE seat_hold (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id     BIGINT      NOT NULL,
    schedule_id BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    booking_id  BIGINT,               -- set when the hold is converted to a booking
    expires_at  TIMESTAMPTZ NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_hold_seat     FOREIGN KEY (seat_id)     REFERENCES seat(id),
    CONSTRAINT fk_hold_schedule FOREIGN KEY (schedule_id) REFERENCES schedule(id),
    CONSTRAINT fk_hold_user     FOREIGN KEY (user_id)     REFERENCES app_user(id),
    CONSTRAINT fk_hold_booking  FOREIGN KEY (booking_id)  REFERENCES booking(id),
    CONSTRAINT ck_hold_status CHECK (status IN ('ACTIVE', 'CONFIRMED', 'EXPIRED', 'RELEASED'))
);

-- STRUCTURAL OVERBOOKING GUARD #2 (per seat): a seat can have at most ONE live claim
-- (an ACTIVE hold or a CONFIRMED booking) at any instant. Two concurrent hold attempts
-- on the same seat race to INSERT here; exactly one wins, the other fails this partial
-- unique index. This is what makes double-booking impossible at the database layer.
CREATE UNIQUE INDEX uq_seat_hold_live ON seat_hold(seat_id) WHERE status IN ('ACTIVE', 'CONFIRMED');
-- Supports the hold-expiry sweep job (Phase 4).
CREATE INDEX idx_hold_active_expires ON seat_hold(expires_at) WHERE status = 'ACTIVE';
CREATE INDEX idx_hold_booking ON seat_hold(booking_id);

CREATE TABLE booking_passenger (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT       NOT NULL,
    seat_id    BIGINT       NOT NULL,
    name       VARCHAR(120) NOT NULL,
    age        INT          NOT NULL,
    gender     VARCHAR(10)  NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'CONFIRMED',
    CONSTRAINT fk_passenger_booking FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE,
    CONSTRAINT fk_passenger_seat    FOREIGN KEY (seat_id)    REFERENCES seat(id),
    CONSTRAINT ck_passenger_age    CHECK (age > 0 AND age < 120),
    CONSTRAINT ck_passenger_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT ck_passenger_status CHECK (status IN ('CONFIRMED', 'WAITLISTED', 'RAC', 'CANCELLED'))
);

CREATE INDEX idx_passenger_booking ON booking_passenger(booking_id);
-- Defense in depth: the same seat cannot appear on two active passenger records.
CREATE UNIQUE INDEX uq_passenger_seat_active ON booking_passenger(seat_id) WHERE status IN ('CONFIRMED', 'RAC');

CREATE TABLE payment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT        NOT NULL,
    amount      NUMERIC(10, 2) NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    gateway_ref VARCHAR(80),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES booking(id),
    CONSTRAINT ck_payment_status CHECK (status IN ('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_payment_amount CHECK (amount >= 0)
);

CREATE INDEX idx_payment_booking ON payment(booking_id);
